### ISSUE TITLE
Support multiple scopes

### ISSUE THREAD

**Issue by provokateurin** [hyiso/commitlint#10]
It seems like multiple scopes are supported in other tools like https://github.com/conventional-changelog/commitlint/pull/901. Would it be possible to implement that here as well? A lot of dart/flutter projects are monorepos and thus can make good use of that.

**Comment by provokateurin** [comment]
Thanks for the fast update ❤️

**Comment by provokateurin** [comment]
Can you make a new release with this feature?

**Comment by hyiso** [comment]
A new version `0.5.0` is released
