### ISSUE TITLE
Support body in commit message

### ISSUE THREAD

**Issue by Leptopoda** [hyiso/commitlint#13]
> A commit body is free-form and MAY consist of any number of newline separated paragraphs.

Currently a body in a commit message breaks the ci while the local git hook succeds

**Comment by hyiso** [comment]
It seems to be a bug in reading commits messages from git log history, I'll check it

**Comment by hyiso** [comment]
`0.6.1` is released

**Comment by Leptopoda** [comment]
Looks like CI is passing again :)
Thank you for the fast fix.
