### ISSUE TITLE
Add `references-empty` rule

### ISSUE THREAD

**Issue by ManuelRauber** [hyiso/commitlint#17]
Hi!

In the JavaScript version of commitlint, there is a rule `references-empty` that can check for ticket numbers like:

```
feat: foo bar 

#3
```

or 

```
feat: foo bar

PROJ-23
```

It would be nice, if you can support those as well. 

Thanks! :)

**Comment by hyiso** [comment]
@ManuelRauber v0.7.0 is release to support `references-empty` rule

**Comment by KeidsID** [comment]
Is it possible to modify the reference prefix like commitlint.js does?

```ts
import { RuleConfigSeverity, UserConfig } from "@commitlint/types";

const config: UserConfig = {
  extends: ["@commitlint/config-conventional"],
  parserPreset: {
    parserOpts: {
      issuePrefixes: "sv-", // `<type>: <msg> sv-<issue-num>` pattern
    },
  },
  rules: {
    "references-empty": [RuleConfigSeverity.Error, "never"],
    "scope-enum": [
      RuleConfigSeverity.Error,
      "always",
      [...],
    ],
  },
};

export default config;
```

Because only `#<issue-num>` pattern are allowed for now.

![image](https://github.com/user-attachments/assets/3289162f-de9a-4c9e-96a6-35389a8a529c)

**Comment by hyiso** [comment]
@KeidsID 
This issue was closed, please file a new issue to trace your problem.
