### ISSUE TITLE
Optional parts like body, footer

### ISSUE THREAD

**Issue by calipee** [hyiso/commitlint#18]
Hi,

is it possible to set rules for optional parts?

For example it should be optional to add a body, but if a body is added `body-leading-blank` should be enforced.

When I tried setting this up there is always an error when there is no body.

**Comment by calipee** [comment]
I believe it's currently not possible. 
I've created a [fork](https://github.com/calipee/commitlint), where I added to option to make rules optional when the corresponding part doesn't exist.

This is a really **hacky** solution but it works for now. 
I won't open a pull requests but maybe it could be used as an inspiration to implement this feature properly.

**Comment by hyiso** [comment]
This seems to be a bug, `leading-blank` rule should ignore null body and footer
