### ISSUE TITLE
Ignore fixup commits

### ISSUE THREAD

**Issue by provokateurin** [hyiso/commitlint#6]
When using the commit-msg hook it would be nice to ignore fixup commits. For CI purposes I see that it could make sense to block them since you don't want to merge fixup commits, but that's not the goal of this tool.

My workaround for this is just using this as the hook: `sed "s/^fixup! //" < "$1" | dart run commitlint_cli`

**Comment by hyiso** [comment]
Do you mean you want this package do nothing if the commit message contains some characters?

**Comment by provokateurin** [comment]
Exactly, it should just allow commits with certain prefixes like `!fixup `

**Comment by hyiso** [comment]
`0.6.0-pre.0` is released with this support
